#CFILES += scf_string.c
#CFILES += scf_list_test.c
#CFILES += scf_stack_test.c
#CFILES += scf_vector_test.c
#CFILES += scf_graph_test.c
#CFILES += scf_graph.c
CFILES += scf_rbtree.c

CFLAGS += -g -O3

LDFLAGS +=

all:
	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

