CFILES += ../util/scf_string.c
CFILES += scf_lex.c
CFILES += ../core/scf_lex_word.c
CFILES += scf_lex_test.c

CFLAGS += -g 
CFLAGS += -I../util
CFLAGS += -I../core

LDFLAGS +=

all:
	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

