CFILES += ../util/scf_string.c
CFILES += scf_elf.c
CFILES += scf_elf_x64.c
CFILES += scf_elf_test.c

CFLAGS += -g
#CFLAGS += -Wall 
CFLAGS += -I../util

LDFLAGS +=

all:
	gcc $(CFLAGS) $(CFILES) $(LDFLAGS)

